### PR TITLE
fix starlark link

### PR DESCRIPTION
**Pull request by shyim**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Comment by letFunny** [comment]
Hi @shyim, I can see that no files were changes in your commit, is that intentional?

**Comment by shyim** [comment]
whoopsie. fixed. :)

**Review by letFunny — APPROVED** [review]
Thanks

**Review by rebornplusplus — APPROVED** [review]
Good catch, thanks!

**Comment by shyim** [comment]
When you rerun the CLA check it should be fine then
image

**Comment by cjdcordeiro** [comment]
Thanks. I'm merging it since it's a doc-related simple fix.

**Pull request merged**
