### PR TITLE
slicer/test: Set archive options from release

### PR DESCRIPTION
**Pull request by woky**
Currently testArchive.Options() returns archive.Options with only the
Arch field set. In future we would like to extend testArchive to behave
differently based on its chisel.yaml definition.

Initialize archive.Options from setup.Release and store it in the
testArchive structure for each archive defined in chise.yaml.

### CODE REVIEW

**Comment by woky** [comment]
This PR depends on #81

**Review by rebornplusplus — APPROVED** [review]
LGTM. You could probably add the Simple label to this one.

**Review by cjdcordeiro — APPROVED** [review]
lgtm, ty

**Comment by flotter** [comment]
> Currently testArchive.Options() returns archive.Options with only the Arch field set. In future we would like to extend testArchive to behave differently based on its chisel.yaml definition.
> 
> Initialize archive.Options from setup.Release and store it in the testArchive structure for each archive defined in chise.yaml.

Just for incase you plan to use this in the commit, the last file name has a typo.

**Review by flotter — APPROVED** [review]
LGTM

**Review by niemeyer — APPROVED** [review]
LGTM

**Pull request merged**
